### ISSUE TITLE
[Security]成績上傳 

### ISSUE THREAD

**Issue by tpchris1** [b0w1d/NTHU_ScoreSharing#1]
是不是上傳成績的時候，可以跟用戶保證一下安全性的問題，謝謝

**Comment by cccccroge** [comment]
在切換各學期的分布圖時，可以新增"雙擊來isolate某個學期的分布圖"功能嗎?
因為很多時候會只想看某學期的，一個個切這樣要切很多次。

**Comment by jjjjj19980806** [comment]
在目前的版本裡，上傳的只有成績分布和學號，所以不會有個人資料外洩的問題。
