### ISSUE TITLE
微調分布圖顯示功能

### ISSUE THREAD

**Issue by cccccroge** [b0w1d/NTHU_ScoreSharing#2]
在切換各學期的分布圖時，可以新增"雙擊來isolate某個學期的分布圖"功能嗎?
因為很多時候會只想看某學期的，一個個切這樣要切很多次。

**Comment by jjjjj19980806** [comment]
為了因應學校的新政策，在近期會改版成績分布的顯示方式。
屆時會參考您的意見，謝謝。
