### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by pp253** [b0w1d/NTHU_ScoreSharing#3]
您好，
請問貴站是否能允許他站 (如清大簡易選課) 使用API?
感謝!

**Comment by b0w1d** [comment]
嗨
我們沒有特別擋任何 domain，關於 CORS 的設定也都和一開始一樣（Allow-Origin = *）
目前是只要沒有會造成負擔的異常行為，我們不會特別做什麼限制
所以我們也不確定是什麼原因造成的?
